version: '3.8'

services:
  web1:
    build: 
      context: ./even
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - 5000:5000
  web2:
    build: 
      context: ./odd
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    ports:
      - 8000:8000
  nginx:
    build: ./nginx/
    ports:
      - 1337:80
    depends_on:
      - web1
      - web2